<link rel="stylesheet" href="bootstrap/css/bootstrap.css">
<link rel="stylesheet" href="assets/css/common.css">
<link rel="stylesheet" href="assets/css/default-style.min.css">
<link rel="stylesheet" href="assets/css/labels.css">
<link rel="stylesheet" href="assets/css/fonts.css">
<link rel="stylesheet" href="assets/css/jquery-ui.min.css">
<link rel="stylesheet" href="assets/css/fullcalendar.min.css">
<link rel="stylesheet" href="assets/css/jquery.ui.timepicker.css">
<link rel="stylesheet" href="assets/css/bootstrap-popover-x.min.css">
<link rel="stylesheet" href="assets/css/bootstrap-toggle.min.css">
<link rel="stylesheet" href="assets/css/checkbox-x.min.css">
<link rel="stylesheet" href="assets/css/morris.css">
